### ISSUE TITLE
QA_Order-of-the-menu_Direct Shear Test Experiment

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#100]
Defect Description :
The order of the menu items for this experiment is not in desired order. Need to correct the order to "Introduction, Theory, Objective, Manual, Procedure, Experiment, Quizzes,  and Feedback".

Actual Result :
The order of the menu items for this experiment is not in desired order. The order of the menu items are given as "Introduction, Theory, Objective, Experiment, Manual, Quizzes, Procedure, Feedback"

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i45](https://cloud.githubusercontent.com/assets/13479177/26487184/02bbcada-421c-11e7-8d6e-91a1565371e9.png)

**Comment by sravanthimodepu** [comment]
The order of the menu items arranged as given "Introduction, Theory, Objective, Experiment, Manual, Quizzes, Procedure, Further readings, Feedback". Hence issue is resolved.

**Comment by BSravanthi** [comment]
Closed #100
