### ISSUE TITLE
QA_Soil-mechanics_Direct Shear Test Experiment_Theory_improper-alignment-for-numbering

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#101]
Defect Description :
In the Theory page of "Direct Shear Test Experiment" experiment, the alignment of the numbering can be given even more neatly. To maintain the look and feel of the page need to correct the alignment.

Actual Result :
In the Theory page of "Direct Shear Test Experiment" experiment, the alignment of the numbering is improper.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i46](https://cloud.githubusercontent.com/assets/13479177/26487268/6d09b460-421c-11e7-8a93-00f6d3c3c5ac.png)

**Comment by sravanthimodepu** [comment]
Aligned the content properly. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #101
