### ISSUE TITLE
QA_soil-mechanics_Direct Shear Test Experiment_Experiment_flash-view-is-disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#102]
Defect Description :
In the Flash view unit of Experiment section in "Direct Shear Test Experiment" - (Flash view on Direct Shear Test Experiment(Click here)) experiment, the flash view is not displaying in the small screen. Where as the flash view is opening in full screen.

Actual Result :
In the Flash view unit of Experiment section in "Direct Shear Test Experiment" - (Flash view on Direct Shear Test Experiment(Click here)) experiment, the flash view is not displaying in the small screen.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i47](https://cloud.githubusercontent.com/assets/13479177/26487623/d6b8f60e-421d-11e7-8076-eba706e8d2f2.png)

**Comment by sravanthimodepu** [comment]
Flash simulation is displaying on the small screen. Differing the issue.

**Comment by BSravanthi** [comment]
Closed #104
