### ISSUE TITLE
QA_Soil-mechanics_Direct Shear Test Experiment_Manual_improper-alignment-for-numbering

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#103]
Defect Description :
In the Manual page of "Direct Shear Test Experiment" experiment, the alignment is improper

Actual Result :
In the Manual page of "Direct Shear Test Experiment" experiment, the alignment is improper

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i48](https://cloud.githubusercontent.com/assets/13479177/26488135/d3db0966-421f-11e7-834b-42781defe0a2.png)

**Comment by sravanthimodepu** [comment]
Table in the page is an image, so cannot modify the table. Hence differing the issue.

**Comment by BSravanthi** [comment]
Closing the differed issue #103
