### ISSUE TITLE
QA_soil-mechanics_Direct Shear Test Experiment_Procedure_Imroper-alignment

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#104]
Defect Description :
In the procedure section of "Direct Shear Test Experiment" - unwanted text is present and the alignment is also improper.

Actual Result :
In the procedure section of "Direct Shear Test Experiment" - unwanted text is present and the alignment is also improper.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i49](https://cloud.githubusercontent.com/assets/13479177/26517999/6ab93bc0-42c3-11e7-876f-2df5713364db.png)

**Comment by sravanthimodepu** [comment]
Table in the page is an image, so cannot modify the table. Hence differing the issue.

**Comment by BSravanthi** [comment]
Closed #104
