### ISSUE TITLE
QA_Soil-mechanics_Direct Shear Test Experiment_Further-readings_irrelevant-content/content-needs-to-be-updated

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#105]
Defect Description :
In the Further readings page of "Direct Shear Test Experiment" experiment, the content needs to be updated.

Actual Result :
In the Further readings page of "Direct Shear Test Experiment" experiment, the content needs to be updated.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i50](https://cloud.githubusercontent.com/assets/13479177/26518009/dc2b3236-42c3-11e7-90ec-f0fb5487a04f.png)

**Comment by sravanthimodepu** [comment]
There is no data to update. Hence removing the section and closing the issue.

**Comment by BSravanthi** [comment]
Closed #105
