### ISSUE TITLE
QA_soil-mechanics_Triaxial Test Experiment_Experiment_flash-view-is-disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#106]
Defect Description :
In the Flash view unit of Experiment section in "Triaxial Test Experiment" - (Flash view on Triaxial Test Experiment(Click here)) experiment, the flash view is not displaying in the small screen. Where as the flash view is opening in full screen.

Actual Result :
In the Flash view unit of Experiment section in "Triaxial Test Experiment" - (Flash view on Triaxial Test Experiment(Click here)) experiment, the flash view is not displaying in the small screen.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i51](https://cloud.githubusercontent.com/assets/13479177/26518063/86122d08-42c5-11e7-87f1-947acb13e760.png)

**Comment by sravanthimodepu** [comment]
Simulation is enabled on small screen. Hence differing this issue.
![triaxial](https://user-images.githubusercontent.com/11156924/27634234-2e835214-5c20-11e7-9f8e-dd1f90e33a64.png)

**Comment by BSravanthi** [comment]
Closed #106
