### ISSUE TITLE
QA_soil-mechanics_Triaxial Test Experiment_Experiment_Name-differing

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#107]
Defect Description :
In the Experiment Unit of the Experiment section in "Triaxial Test Experiment" , the name of the unit is given as **Flash view on Traixial Test Experiment(Click here)**. But, on click-full screen, the link is navigating to the simulator. Instead the naming should be appropriate to the experiment page.

Actual Result :
In the Experiment Unit of the Experiment section in "Triaxial Test Experiment" , the name of the unit is given as **Flash view on Traixial Test Experiment(Click here)**. But, on click-full screen, the link is navigating to the simulator. Instead the naming should be appropriate to the experiment page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i52](https://cloud.githubusercontent.com/assets/13479177/26518149/e215ac68-42c7-11e7-916d-ab55aea776bf.png)

**Comment by sravanthimodepu** [comment]
Updated the simulation name accordingly. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Issue is reopened as there are 2 units in the simulation section of this experiment. One is flash view and the other is the experiment link. While fixing the developer team has removed the flash view unit and kept the experiment unit back. 
For this unit also the title is not given. 

Refer to the attachments:


![qa_oe_sm_i56](https://user-images.githubusercontent.com/13479177/27624918-584a270a-5c00-11e7-9f12-79a2d58579cf.png)

**Comment by sravanthimodepu** [comment]
Added the 2nd simulation for the experiment. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #107
