### ISSUE TITLE
QA_soil-mechanics_Triaxial Test Experiment_Manual_table-alignment-is-improper

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#108]
Defect Description :
In the Manual page of "Triaxial Test Experiment" experiment, the alignment of the table is improper. To improve the look and feel of the page, Need to maintain consistency.

Actual Result :
In the Manual page of "Triaxial Test Experiment" experiment, the alignment of the table is improper.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i53](https://cloud.githubusercontent.com/assets/13479177/26518198/0ded1438-42c9-11e7-8de8-1dc1edc363af.png)

**Comment by sravanthimodepu** [comment]
Table in the page is an image, so cannot modify the table. Hence differing the issue.

**Comment by BSravanthi** [comment]
Closing the differed issue #108
