### ISSUE TITLE
QA_soil-mechanics_Triaxial Test Experiment_Procedure_table-alignment-is-improper

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#109]
Defect Description :
In the Procedure page of "Triaxial Test Experiment" experiment, the alignment of the table is improper. To improve the look and feel of the page, Need to maintain consistency.

The content of Manual and Procedure sections is same.

Actual Result :
In the Procedure page of "Triaxial Test Experiment" experiment, the alignment of the table is improper. The content of Manual and Procedure sections is same.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i54](https://cloud.githubusercontent.com/assets/13479177/26518235/f71ff2d8-42c9-11e7-8ebc-611123080221.png)

**Comment by sravanthimodepu** [comment]
Table in the page is an image, so cannot modify the table. Hence closing the issue.

**Comment by BSravanthi** [comment]
Closed the differed issue #109
