### ISSUE TITLE
QA_Soil-mechanics_Triaxial Test Experiment_Further-readings_irrelevant-content/content-needs-to-be-updated

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#110]
Defect Description :
In the Further readings page of "Triaxial Test Experiment" experiment, the content needs to be updated.

Actual Result :
In the Further readings page of " Experiment" experiment, the content needs to be updated.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i55](https://cloud.githubusercontent.com/assets/13479177/26518256/74740f44-42ca-11e7-9402-c1fff4783eeb.png)

**Comment by sravanthimodepu** [comment]
There is no content to port from vlab.co.in . Hence removing the section.

**Comment by BSravanthi** [comment]
Closed #110
