### ISSUE TITLE
QA_Soil-mechanics_Atterberg Limits Experiment_name-of-the-experiment-differs

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#111]
Defect Description :
The name of the experiment in the vlabs page is "Attenberg Limits", where as in the open edx the name is given as "Atterberg Limits Experiment". Need to correct the name according to the vlabs page.

Actual Result :
The name of the experiment in the vlabs page is "Attenberg Limits", where as in the open edx the name is given as "Atterberg Limits Experiment". 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i58](https://user-images.githubusercontent.com/13479177/27627147-540c0480-5c08-11e7-934b-1fb7fdc094a2.png)

**Comment by sravanthimodepu** [comment]
Correct spelling is Atterberg, so modify Atternberg toAtterberg.

**Comment by BSravanthi** [comment]
Closed #111
