### ISSUE TITLE
QA_soil-mechanics_Specific Gravity Experiment_titles-are-missing

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#112]
Referenced to issue #66. 
While fixing that issue, names for the both units in the experiment section have been removed. In order to maintain the clarity for users need to give names to both the units.

![qa_oe_sm_i60](https://user-images.githubusercontent.com/13479177/27628695-779c8960-5c0d-11e7-8a54-ff53bfafe934.png)

**Comment by sravanthimodepu** [comment]
Added names for the both experiments. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #112
