### ISSUE TITLE
QA_Compaction Test_Further Readings_p2

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#12]
Defect Description :
In the Further Readings page of "Compaction Test" experiment,when we click on the "www.engineeringcivil.com/soil-compaction-tests.html" link it is redirecting to an error page(404) instead it should redirect to a new tab with the selected link

Actual Result :
In the Further Readings page of "Compaction Test" experiment ,when we click on the "www.engineeringcivil.com/soil-compaction-tests.html" link it is redirecting to an error page(404).

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith/blob/master/test-cases/integration_test-cases/Compaction%20Test/Compaction%20Test_20_Further%20Readings_p2.org

Attachment:
![sm35](https://cloud.githubusercontent.com/assets/14869397/14779461/e4217fe2-0af5-11e6-9052-df9c342ca181.png)

**Comment by khushpreet-kaur** [comment]
Issue is fixed. Link is working fine now.

**Comment by khushpreet-kaur** [comment]
Issue is fixed. Link is working fine now.

**Comment by BSravanthi** [comment]
Closed  #12
