### ISSUE TITLE
QA_Attenberg Limits_Prerequisites_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#21]
Defect Description :
In the "Attenberg Limits" experiment, the minimum requirement to run the experiment is not displayed in the page instead a page or Scrolling should appear providing information on minimum requirement to run this experiment, information like Bandwidth,Device Resolution,Hardware Configuration and Software Required.

Actual Result :
In the "Attenberg Limits" experiment, the minimum requirement to run the experiment is not displayed in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith/blob/master/test-cases/integration_test-cases/Attenberg%20Limits/Attenberg%20Limits_21_Prerequisites_p1.org

Attachment:
![sm26](https://cloud.githubusercontent.com/assets/14869397/14779164/71b09642-0af4-11e6-8aeb-45998b80325a.png)

**Comment by khushpreet-kaur** [comment]
This is not part of design, User will automatically get redirected to installation page.

**Comment by khushpreet-kaur** [comment]
This is not part of design, user will automatically gets redirected to installation page in case of missing pre-requisites.

**Comment by BSravanthi** [comment]
Closed  #21
