### ISSUE TITLE
QA_Attenberg Limits_Experiment_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#23]
Defect Description :
In the Experiment page of "Attenberg Limits " experiment, when we click on the "Go to Virtual lab on Attenberg Limits" link, it is redirecting to a blank page instead it should redirect to an experiment page  in-order to perform the simulation of the experiment

Actual Result :
In the Experiment page of "Attenberg Limits " experiment, when we click on the "Go to Virtual lab on Attenberg Limits" link, it is redirecting to a blank page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith/blob/master/test-cases/integration_test-cases/Attenberg%20Limits/Attenberg%20Limits_10_Experiment_p1.org

Attachment:
![sm24](https://cloud.githubusercontent.com/assets/14869397/14779141/477d412c-0af4-11e6-8701-9411c3793476.png)

**Comment by khushpreet-kaur** [comment]
Link is working fine now.

**Comment by BSravanthi** [comment]
Closed #34 23
