### ISSUE TITLE
Syntactical and Semantical Issues on the main page

### ISSUE THREAD

**Issue by SiddarthVijay** [virtual-labs/soil-mechanics-and-foundation-engineering-iiith#270]
Just replace the existing description on (http://smfe-iiith.vlabs.ac.in/) with,

Soil is a very important engineering material. Determination of soil conditions is the most significant task in every civil engineering activity. Properties of the soil can be determined by using both field and laboratory testing methods. It is critical to quantify the various properties of soil in order to predict its behavior under different conditions, for the safe design of structures. The soil mechanics and foundation engineering laboratory is a compulsory and basic undergraduate course where an introduction to Geotechnical Engineering will be provided and this course can also be taken up by graduate level research students.

The use of the virtual laboratory allows the students to understand the numbers behind the information associated with the laboratory experiments. Generally, engineering faculty will provide the experimental procedure to the student group just before doing the experiment in the lab. With the virtualization of the laboratory experiments, the students can explore the experimental procedures prior to actually performing it in the laboratory, and are therefore being much more informed on what is to be done in the laboratory and what results to expect.

The main objectives of developing the soil mechanics and foundation engineering virtual lab will be: 1. Students should be able to carry out all soil mechanics fundamental experiments according to standards 2. To analyze and interpret experimental data. 3. To understand the techniques, skills and modern engineering tools necessary for engineering practice In this proposal, different laboratory tests can be developed for conducting the following important experiments to estimate the mechanical and engineering properties of soils.

**Comment by samhithavootkoor** [comment]
fixed
commit id: f11abb0

**Comment by abhishek5460** [comment]
Validated -1 @samhithavootkoor

**Comment by niveditareddy** [comment]
Valid fix @samhithavootkoor

**Comment by DevikaBoddu** [comment]
Valid fix @samhithavootkoor
