### ISSUE TITLE
QA_Triaxial Test_Experiment_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#3]
Defect Description :
In the Experiment page of "Triaxial Test " experiment, when we click on the " Go to Virtual lab on Triaxial Test" link, it is redirecting to a blank page instead it should redirect to an experiment page  in-order to perform the simulation of the experiment

Actual Result :
In the Experiment page of "Triaxial Test " experiment, when we click on the " Go to Virtual lab on Triaxial Test" link, it is redirecting to a blank page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith/blob/master/test-cases/integration_test-cases/Triaxial%20Test/Triaxial%20Test_10_Experiment_p1.org

Attachment:
![sm44](https://cloud.githubusercontent.com/assets/14869397/14779678/dee636a2-0af6-11e6-9a27-da94bd8c2453.png)

**Comment by khushpreet-kaur** [comment]
Link is working fine now.

**Comment by BSravanthi** [comment]
The link is working if the Java 3D is installed in the machine. Link is working fine, hence closed #30
