### ISSUE TITLE
QA_Specific Gravity_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#30]
Defect Description :
In the "Specific Gravity" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user. 

Actual Result :
In the "Specific Gravity" experiment,the back to experiments link is not present in the page. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5
 Test Step Link:
https://github.com/Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith/blob/master/test-cases/integration_test-cases/Specific%20Gravity/Specific%20Gravity_22_Back%20to%20experiments_smk.org

Attachment;
![sm17](https://cloud.githubusercontent.com/assets/14869397/14779021/b904138a-0af3-11e6-8d8c-706a6a3fee4c.png)

**Comment by khushpreet-kaur** [comment]
Issue is resolved now.

**Comment by BSravanthi** [comment]
Closed  #30
