### ISSUE TITLE
QA_Specific Gravity_Further Readings_p2

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#31]
Defect Description :
In the Further Readings page of "Specific Gravity" experiment ,when we click on the "http://geology.csupomona.edu/alert/mineral/gravity.htm" link it is redirecting to an error page instead it should redirect to a new tab with the selected link 

Actual Result :
In the Further Readings page of "Specific Gravity" experiment ,when we click on the "http://geology.csupomona.edu/alert/mineral/gravity.htm" link it is redirecting to an error page. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5
 Test Step Link:
https://github.com/Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith/blob/master/test-cases/integration_test-cases/Specific%20Gravity/Specific%20Gravity_20_Further%20Readings_p2.org

Attachment:
![sm16](https://cloud.githubusercontent.com/assets/14869397/14778985/8f020006-0af3-11e6-8e80-0bb0e2e16d61.png)

**Comment by khushpreet-kaur** [comment]
Issue is fixed now. Link is working fine.

**Comment by khushpreet-kaur** [comment]
Issue is fixed now. Link is working fine.

**Comment by khushpreet-kaur** [comment]
Issue is fixed now. Link is working fine.

**Comment by khushpreet-kaur** [comment]
Issue is fixed now. Link is working fine.

**Comment by BSravanthi** [comment]
@khushpreet-kaur The link is still not working.

**Comment by khushpreet-kaur** [comment]
@BSravanthi  This link has been removed from the official source. So removing link from this page for now.

**Comment by khushpreet-kaur** [comment]
Link has been replace with http://archive.is/geology.csupomona.edu  as per Lalit's decision.

**Comment by BSravanthi** [comment]
Closed #31
