### ISSUE TITLE
QA_Unit Weight_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#36]
Defect Description :
In the "Unit Weight" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user.  

Actual Result :
In the "Unit Weight" experiment,the back to experiments link is not present in the page. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5
 Test Step Link:
https://github.com/Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith/blob/master/test-cases/integration_test-cases/Unit%20Weight/Unit%20Weight_22_Back%20to%20experiments_smk.org

Attachment:
![sm11](https://cloud.githubusercontent.com/assets/14869397/14778898/2cc729de-0af3-11e6-8f2b-20631685b848.png)

**Comment by khushpreet-kaur** [comment]
This issue is resolved now as UI has been changed to UI3.0.

**Comment by BSravanthi** [comment]
Closed #36
