### ISSUE TITLE
QA_Water Content_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#41]
Defect Description :
In the "Water Content" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user.  

Actual Result :
In the "Water Content" experiment,the back to experiments link is not present in the page. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5
 Test Step Link:
https://github.com/Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith/blob/master/test-cases/integration_test-cases/Water%20Content/Water%20Content_21_Back%20to%20experiments_smk.org

Attachment:
![sm6](https://cloud.githubusercontent.com/assets/14869397/14778776/85979a68-0af2-11e6-9070-82e5fde50e74.png)

**Comment by khushpreet-kaur** [comment]
Issue is resolved now with UI 3.0.

**Comment by BSravanthi** [comment]
Closed #41
