### ISSUE TITLE
QA_Soil Mechanics_Feedback_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#45]
Defect Description :
In the feedback page of "Soil Mechanics" Lab home page ,when we click on the feedback link it is redirecting to an error page(404) instead it should redirect to the feedback page.  

Actual Result :
In the feedback page of "Soil Mechanics" Lab home page ,when we click on the feedback link it is redirecting to an error page(404). 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5
 Test Step Link:
https://github.com/Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith/blob/master/test-cases/integration_test-cases/Soil%20Mechanics/Soil%20Mechanics_08_Feedback_p1.org

Attachment:
![sm2](https://cloud.githubusercontent.com/assets/14869397/14778720/2f0c99a0-0af2-11e6-8f6f-12266002d27b.png)

**Comment by khushpreet-kaur** [comment]
Link is working fine now. Issue is resolved.

**Comment by BSravanthi** [comment]
closed #45
