### ISSUE TITLE
QA_Soil Mechanics_Usability_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#46]
Defect Description :
In the Home page of  "Soil Mechanics" Lab, the "Home" & "Soil Mechanics Lab" links are not present inside the page instead the links should be present inside the page in-order to maintain the page utility  

Actual Result :
In the Home page of  "Soil Mechanics" Lab, the "Home" & "Soil Mechanics Lab" links are not present inside the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5
 Test Step Link:
https://github.com/Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith/blob/master/test-cases/integration_test-cases/Soil%20Mechanics/Soil%20Mechanics_01_Usability_smk.org

**Comment by khushpreet-kaur** [comment]
UI has been changed. And all the links are consistent as per UI3.0

**Comment by BSravanthi** [comment]
Closed #46.
