### ISSUE TITLE
Update the old footer to new

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#48]
@khushpreet-kaur 
The footer needs to be updated from UI 1.0 to UI 3.0 in the Quizzes page of the Experiments 1,2,3,4,6 and 7.

**Comment by khushpreet-kaur** [comment]
@BSravanthi  This issue is resolved now. All files are updated with new footer.

**Comment by BSravanthi** [comment]
Closed #48
