### ISSUE TITLE
Search Box Option need to be removed in  Grain Size Distribution Experiment.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#50]
In the "Feedback" page of the Grain Size Distribution Experiment of Soil Mechanics lab, **Search Box** option is given on the top right corner, where as in all the pages of all the experiments no **Search Box** option is given.

**Comment by khushpreet-kaur** [comment]
Search box has been commented out. Issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #50
