### ISSUE TITLE
QA_Order-of-the-menu_Water Content Experiment

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#54]
Defect Description :
The order of the menu items for this experiment is not in desired order. Need to correct the order to "Introduction, Theory, Objective, Manual, Procedure, Experiment, Quizzes, Further readings and Feedback".

Actual Result :
The order of the menu items for this experiment is not in desired order. The order of the menu items are given as "Introduction, Theory, Objective, Experiment, Manual, Quizzes, Procedure, Further readings, Feedback"

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i02](https://cloud.githubusercontent.com/assets/13479177/26440902/fccf7e1c-414b-11e7-9e49-fd62e0b2c46f.png)

**Comment by sravanthimodepu** [comment]
Arranged the menu in proper order. Hence issue is fixed.

**Comment by BSravanthi** [comment]
Closed #54
