### ISSUE TITLE
QA_Soil-mechanics_Water Content Experiment_Introduction_improper-alignment

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#55]
Defect Description :
In the Introduction page of "Water Content Experiment" experiment, the alignment of the content is improper.

Actual Result :
In the Introduction page of "Water Content Experiment" experiment, the alignment of the content is improper.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_os_sm_i01](https://cloud.githubusercontent.com/assets/13479177/26440970/4d887f0c-414c-11e7-9dee-479abb1ebe7b.png)

**Comment by sravanthimodepu** [comment]
Aligned the content properly. Hence the issue is fixed.

**Comment by BSravanthi** [comment]
Closed #55
