### ISSUE TITLE
QA_Soil-mechanics_Water Content Experiment_Theory_improper-alignment

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#56]
Defect Description :
In the Theory page of "Water Content Experiment" experiment, the alignment of the content is improper.

Actual Result :
In the Theory page of "Water Content Experiment" experiment, the alignment of the content is improper.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i03](https://cloud.githubusercontent.com/assets/13479177/26441156/0529370a-414d-11e7-877a-e517c2ebba42.png)

**Comment by sravanthimodepu** [comment]
Aligned the content properly. Hence the issue is fixed.

**Comment by BSravanthi** [comment]
Closed #56
