### ISSUE TITLE
QA_soil-mechanics_Water Content Experiment_Experiment_flash-view-is-disabled-in-small-scree.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#57]
Defect Description :
In the Experiment page of "Water Content Experiment" - (Flash view on Water Content Experiment(Click here))experiment, the flash view is not displaying in the small screen. Where as the experiment is opening in full screen.

Actual Result :
In the Experiment page of "Water Content Experiment" - (Flash view on Water Content Experiment(Click here))experiment, the flash view is not displaying in the small screen. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i04](https://cloud.githubusercontent.com/assets/13479177/26442915/1ce7d2e6-4154-11e7-8284-75bf1079be04.png)

**Comment by sravanthimodepu** [comment]
Differing the issue, as the flash view of the simulation is displaying on the screen.
![water](https://user-images.githubusercontent.com/11156924/27673412-3725d10a-5cbe-11e7-9c09-44107c253b34.png)

**Comment by BSravanthi** [comment]
While testing the flash view was disabled. Closed #57 as now the flash view is enabled small screen.
