### ISSUE TITLE
QA_soil-mechanics_Water Content Experiment_Experiment_Irrelevant-text

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#58]
Defect Description :
In the Experiment section of "Water Content Experiment" - (Go to Virtual lab on Water Content Experiment(Click here))experiment, the given text is irrelevant to this experiment. Refer the attachment for details.

Actual Result :
In the Experiment section of "Water Content Experiment" - (Go to Virtual lab on Water Content Experiment(Click here))experiment, the given text is irrelevant to this experiment. Refer the attachment for details.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i05](https://cloud.githubusercontent.com/assets/13479177/26443413/ee658100-4155-11e7-8ccb-f5cf418ba265.png)

**Comment by sravanthimodepu** [comment]
Removed unwanted text from the simulation page. Hence the issue is fixed.

**Comment by BSravanthi** [comment]
Closed #58
