### ISSUE TITLE
QA_soil-mechanics_Water Content Experiment_Experiment_experiment-is-disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#59]
Defect Description :
In the Experiment page of "Water Content Experiment" - (Flash view on Water Content Experiment(Click here))experiment, the Experiment is not displaying in the small screen. Where as the experiment is opening in full screen.

Actual Result :
In the Experiment page of "Water Content Experiment" - (Flash view on Water Content Experiment(Click here))experiment, the Experiment is not displaying in the small screen.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i06](https://cloud.githubusercontent.com/assets/13479177/26443535/70b6e5d6-4156-11e7-8478-a12706579af5.png)

**Comment by sravanthimodepu** [comment]
Flash view of the simulation is displaying on the small screen. Hence differing the issue.

**Comment by BSravanthi** [comment]
While testing the flash view was disabled. Closed #59 as now the flash view is enabled small screen.
