### ISSUE TITLE
QA_Direct Shear Test_Experiment_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#6]
Defect Description :
In the Experiment page of " Direct Shear Test " experiment, when we click on the " Go to Virtual lab on Direct Shear Test" link, it is redirecting to a blank page instead it should redirect to an experiment page  in-order to perform the simulation of the experiment

Actual Result :
In the Experiment page of " Direct Shear Test " experiment, when we click on the " Go to Virtual lab on Direct Shear Test" link, it is redirecting to a blank page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith/blob/master/test-cases/integration_test-cases/Direct%20Shear%20Test/Direct%20Shear%20Test_10_Experiment_p1.org

Attachment:
![sm41](https://cloud.githubusercontent.com/assets/14869397/14779630/a6d95bcc-0af6-11e6-9221-083477d05815.png)

**Comment by khushpreet-kaur** [comment]
Link is working fine now.

**Comment by BSravanthi** [comment]
Closed #6
