### ISSUE TITLE
QA_soil-mechanics_Water Content Experiment_Manual_table-alignment-is-improper

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/soil-mechanics-and-foundation-engineering-iiith#60]
Defect Description :
In the Manual page of "Water Content Experiment" experiment, the alignment of the table is improper. To improve the look and feel of the page, Need to maintain consistency.

Actual Result :
In the Manual page of "Water Content Experiment" experiment, the alignment of the table is improper. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i07](https://cloud.githubusercontent.com/assets/13479177/26443666/fc573bfe-4156-11e7-8cf2-c3505085f26d.png)

**Comment by sravanthimodepu** [comment]
Aligned the table properly. Hence resolved the issue.

**Comment by BSravanthi** [comment]
The alignment of the table is changing according to the zoom in and out. 
Keeping on hold for further clarification from the developer.
