### ISSUE TITLE
QA_soil-mechanics_Water Content Experiment_Quizzes_show-answer-button-needs-to-be-provided

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/soil-mechanics-and-foundation-engineering-iiith#61]
Defect Description :
In the Quizzes page of "Water Content Experiment" experiment, the "Show Answer" button is not provided.

Actual Result :
In the Quizzes page of "Water Content Experiment" experiment, the "Show Answer" button is not provided

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i08](https://cloud.githubusercontent.com/assets/13479177/26445497/0e6965f4-415e-11e7-90fa-c57ea3d52f9f.png)

**Comment by sravanthimodepu** [comment]
Show answer button is existed. Hence differing the issue.

**Comment by BSravanthi** [comment]
Not a differed issue. When logged in as admin the button will be displayed. Where as logged in as user the button will not be displayed. Hence reopening the issue.
