### ISSUE TITLE
QA_soil-mechanics_Unit Weight Experiment_Flash-view_Irrelevant-text

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#62]
Defect Description :
In the Flash view Unit of the Experiment section of  "Unit weight Experiment" - Go to Flash view on Unit Weight Experiment(Click here) experiment, the given text is irrelevant to this experiment. Refer the attachment for details.

Actual Result :
In the Flash view Unit of the Experiment section of  "Unit weight Experiment" - Go to Flash view on Unit Weight Experiment(Click here) experiment, the given text is irrelevant to this experiment. Refer the attachment for details.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i09](https://cloud.githubusercontent.com/assets/13479177/26445962/bdeac6fc-415f-11e7-80b0-2dd9541fac70.png)

**Comment by sravanthimodepu** [comment]
No irrelevant text found in the simulation page. Hence differing the issue.

**Comment by BSravanthi** [comment]
Marked text in the above screen shot is irrelevant. And hence its not a differed issue. 
As the irrelevant text is not existed. closing the issue #62
