### ISSUE TITLE
QA_soil-mechanics_Unit weight Experiment_Experiment_Irrelevant-text

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#63]
Defect Description :
In the Experiment section of "Unit Weight Experiment" - Go to Virtual lab on Unit Weight Experiment(Click here) experiment, the given text is irrelevant to this experiment. Refer the attachment for details.

Actual Result :
In the Experiment section of "Unit Weight Experiment" - Go to Virtual lab on Unit Weight Experiment(Click here) experiment, the given text is irrelevant to this experiment. Refer the attachment for details.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i10](https://cloud.githubusercontent.com/assets/13479177/26446379/66b76eb0-4161-11e7-8223-c277a225e860.png)

**Comment by sravanthimodepu** [comment]
N irrelevant text found in the simulation page. Hence differing the issue.

**Comment by BSravanthi** [comment]
Not a differed issue. The selected text in the screen shot is irrelevant to the current experiment.
As the text is not found in retesting closing the issue. #63
