### ISSUE TITLE
QA_soil-mechanics_Unit weight Experiment_Experiment_flash-view-is-disabled-in-small-scree.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#64]
Defect Description :
In the Experiment page of "Unit weight Experiment" - (Flash view on Unit weight Experiment(Click here))experiment, the flash view is not displaying in the small screen. Where as the Flash view is opening in full screen.

Actual Result :
In the Experiment page of "Unit weight Experiment" - (Flash view on Unit weight Experiment(Click here))experiment, the flash view is not displaying in the small screen.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i11](https://cloud.githubusercontent.com/assets/13479177/26446560/2f3915c8-4162-11e7-9ada-412c201bfb1e.png)

**Comment by sravanthimodepu** [comment]
Differing the issue, as the simulation is displaying on the small screen.
![unit](https://user-images.githubusercontent.com/11156924/27672376-167b6e98-5cb8-11e7-89b9-46ff02d85a97.png)

**Comment by BSravanthi** [comment]
While testing the flash view was disabled. Closed #64 as now the flash view is enabled small screen.
