### ISSUE TITLE
QA_soil-mechanics_Unit weight Experiment_Quizzes_show-answer-button-needs-to-be-provided

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/soil-mechanics-and-foundation-engineering-iiith#65]
Defect Description :
In the Quizzes page of "Unit weight Experiment" experiment, the "Show Answer" button is not provided.

Actual Result :
In the Quizzes page of "Unit weight Experiment" experiment, the "Show Answer" button is not provided

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i12](https://cloud.githubusercontent.com/assets/13479177/26446884/a2150e98-4163-11e7-8719-88390d17a202.png)

**Comment by sravanthimodepu** [comment]
Show answer button is exited in the page. Hence differing the issue.

**Comment by BSravanthi** [comment]
Not a differed issue. Still persisting. Hence re-opening the issue.
