### ISSUE TITLE
QA_soil-mechanics_Specific Gravity Experiment_Flash-view_Irrelevant-text

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#66]
Defect Description :
In the Flash view Unit of the Experiment section of "Specific Gravity Experiment" - **Go to Flash view on Specific Gravity Experiment (Click here)**, the given text is irrelevant to this experiment. Refer the attachment for details.

Actual Result :
In the Flash view Unit of the Experiment section of "Specific Gravity Experiment" - **Go to Flash view on Specific Gravity Experiment (Click here)**, the given text is irrelevant to this experiment. Refer the attachment for details.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i13](https://cloud.githubusercontent.com/assets/13479177/26447643/08f96188-4167-11e7-92e5-8784e96657df.png)

**Comment by sravanthimodepu** [comment]
Removed the unwanted text from the page. Hence issue is fixed.

**Comment by BSravanthi** [comment]
Closed #66
