### ISSUE TITLE
QA_soil-mechanics_Specific Gravity Experiment_Flash-view_breadcrump-is-to-be-provided

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#67]
Defect Description :
In the Flash view Unit of the Experiment section of "Specific Gravity Experiment" - Go to Flash view on Specific Gravity Experiment (Click here), the bread crump is missed. 

Actual Result :
In the Flash view Unit of the Experiment section of "Specific Gravity Experiment" - Go to Flash view on Specific Gravity Experiment (Click here), the bread crump is missed. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i13](https://cloud.githubusercontent.com/assets/13479177/26447798/e0aa27c0-4167-11e7-9df5-b3d09839626e.png)

**Comment by sravanthimodepu** [comment]
Removed unwanted text from the page. Hence issue is fixed.

**Comment by BSravanthi** [comment]
Closed #67
