### ISSUE TITLE
QA_soil-mechanics_Specific Gravity Experiment_Experiment_flash-view-is-disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#68]
Defect Description :
In the Flash view unit of Experiment section in "Specific Gravity Experiment" - (Flash view on Specific Gravity Experiment(Click here)) experiment, the flash view is not displaying in the small screen. Where as the flash view is opening in full screen.

Actual Result :
In the Flash view unit of Experiment section in "Specific Gravity Experiment" - (Flash view on Specific Gravity Experiment(Click here))experiment, the flash view is not displaying in the small screen. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i14](https://cloud.githubusercontent.com/assets/13479177/26448130/534a10fa-4169-11e7-9107-de9066fa1ac1.png)

**Comment by sravanthimodepu** [comment]
Differing this issue, as the flash simulation is enabled on the small screen.

**Comment by BSravanthi** [comment]
While testing the flash view was disabled. Closed #68 as now the flash view is enabled small screen.
