### ISSUE TITLE
QA_soil-mechanics_Specific Gravity Experiment_experiment_breadcrump-is-to-be-provided

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#69]
Defect Description :
In the Experiment Unit of the Experiment section in "Specific Gravity Experiment" - **Go to Virtual lab on Specific Gravity Experiment(Click here)**, the bread crump is missed. 

Actual Result :
In the Experiment Unit of the Experiment section in "Specific Gravity Experiment" - **Go to Virtual lab on Specific Gravity Experiment(Click here)**, the bread crump is missed. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i15](https://cloud.githubusercontent.com/assets/13479177/26448220/d1200de0-4169-11e7-8a12-bc84c507d550.png)

**Comment by sravanthimodepu** [comment]
Bread crumb is displayed on the experiment page.
![specific](https://user-images.githubusercontent.com/11156924/27672013-a57db22a-5cb5-11e7-89a1-5aef1853ea9b.png)

**Comment by BSravanthi** [comment]
Closed #69
