### ISSUE TITLE
QA_soil-mechanics_Specific Gravity Experiment_Quizzes_Unit-Weight-experiment's-questions-are-given

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#70]
Defect Description :
In the Quizzes page of "Specific Gravity Experiment" experiment, all the questions provided in this section are belongs to **Unit weight experiment**. Even in the vlabs page also the questions are of **Unit weight experiment** itself. Instead the questions should be related to "Specific Gravity Experiment" to give the complete information and knowledge to the users about this experiment. 

Actual Result :
In the Quizzes page of "Specific Gravity Experiment" experiment, all the questions provided in this section are belongs to **Unit weight experiment**. Even in the vlabs page also the questions are of **Unit weight experiment** itself.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i16](https://cloud.githubusercontent.com/assets/13479177/26448492/26b2e358-416b-11e7-93e0-74f64bbae91f.png)

**Comment by sravanthimodepu** [comment]
Updated the quiz questions correctly and the questions given in this experiment are not multiple choice, so removed the options for the questions. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #70
