### ISSUE TITLE
QA_Soil-mechanics_Specific Gravity Experiment_Manual_improper-alignment

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#71]
Defect Description :
In the Manual page of "Specific Gravity Experiment" experiment, the alignment of the 1st point is improper.

Actual Result :
In the Manual page of "Specific Gravity Experiment" experiment, the alignment of the 1st point is improper.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i17](https://cloud.githubusercontent.com/assets/13479177/26448626/cba56d4a-416b-11e7-8068-d2a77ccd7d86.png)

**Comment by sravanthimodepu** [comment]
The issue is in the procedure page but not in the manual page. Arranged the steps properly. Hence resolved the issue.

**Comment by BSravanthi** [comment]
@sravanthimodepu  Thanks for correcting me. 
The issue is closed #71
