### ISSUE TITLE
QA_Soil-mechanics_Specific Gravity Experiment_Further-readings_irrelevant-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#72]
Defect Description :
In the Further readings page of "Specific Gravity Experiment" experiment, the 3rd link is navigating to irrelevant page.

Actual Result :
In the Further readings page of "Specific Gravity Experiment" experiment, the 3rd link is navigating to irrelevant page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i18](https://cloud.githubusercontent.com/assets/13479177/26448981/93bfb910-416d-11e7-9718-c9a9be2d58a0.png)

**Comment by sravanthimodepu** [comment]
The 3rd link is related to the simulation. Hence differing this issue.

**Comment by BSravanthi** [comment]
Closed #72
