### ISSUE TITLE
QA_Order-of-the-menu_Specific Gravity Experiment 

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#73]
Defect Description :
The order of the menu items for this experiment is not in desired order. Need to correct the order to "Introduction, Theory, Objective, Manual, Procedure, Experiment, Quizzes, Further readings and Feedback".

Actual Result :
The order of the menu items for this experiment is not in desired order. The order of the menu items are given as "Introduction, Theory, Objective, Experiment, Manual, Quizzes, Procedure, Further readings, Feedback"

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i19](https://cloud.githubusercontent.com/assets/13479177/26449064/e7ec3fe0-416d-11e7-8f84-8e8116e0da27.png)

**Comment by sravanthimodepu** [comment]
The order of the menu items are arranged as "Introduction, Theory, Objective, Experiment, Manual, Quizzes, Procedure, Further readings, Feedback". Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #73
