### ISSUE TITLE
QA_Soil-mechanics_Grain Size Distribution Experiment_Theory_introduction-content-is-given-in-theory-section

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#75]
Defect Description :
In the Theory page of "Grain Size Distribution Experiment" experiment, while porting instead of theory content, Introduction content of **Grain Size Distribution experiment** is given.

Actual Result :
In the Theory page of "Grain Size Distribution Experiment" experiment, while porting instead of theory content, Introduction content of **Grain Size Distribution experiment** is given.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i21](https://cloud.githubusercontent.com/assets/13479177/26449427/bbbf5360-416f-11e7-8dcf-7828e6904a4e.png)

**Comment by sravanthimodepu** [comment]
Updated the theory page with appropriate content. Hence issue is fixed.

**Comment by BSravanthi** [comment]
Closed #75
