### ISSUE TITLE
QA_soil-mechanics_Grain Size Distribution Experiment_experiment_Name-differing

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#76]
Defect Description :
In the Flash view Unit of the Experiment section in "Grain Size Distribution Experiment" , the name of the unit is given as **Go to Flash view on Tensile Test Experiment(Click here)**. But, on click-full screen, the link is navigating to Grain Size Distribution Experiment itself. Even in the vlabs page too, the name was given as **Go to Flash view on Tensile Test Experiment(Click here)**. Instead the naming should be appropriate to the experiment. 

Actual Result :
In the Flash view Unit of the Experiment section in "Grain Size Distribution Experiment" , the name of the unit is given as **Go to Flash view on Tensile Test Experiment(Click here)**. But, on click-full screen, the link is navigating to Grain Size Distribution Experiment itself. Even in the vlabs page too, the name was given as **Go to Flash view on Tensile Test Experiment(Click here)**. Instead the naming should be appropriate to the experiment. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i22](https://cloud.githubusercontent.com/assets/13479177/26450124/76338e16-4173-11e7-8062-7969f5530e8b.png)

**Comment by sravanthimodepu** [comment]
Updated  the simulation name properly. Hence issue is fixed.

**Comment by BSravanthi** [comment]
Issue reopened as,
1. removing the name may not be a solution. 
2. In experiment section earlier 2 units were there, After fixing this issue found only one unit(Flash view). Experiment unit has been removed.

**Comment by sravanthimodepu** [comment]
Added the 2nd simulation to the experiment.Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #76
