### ISSUE TITLE
QA_soil-mechanics_Grain Size Distribution Experiment_Experiment_flash-view-is-disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#77]
Defect Description :
In the Flash view unit of Experiment section in "Grain Size Distribution Experiment" - (Flash view on Grain Size Distribution Experiment(Click here)) experiment, the flash view is not displaying in the small screen. Where as the flash view is opening in full screen.

Actual Result :
In the Flash view unit of Experiment section in "Grain Size Distribution Experiment" - (Flash view on Grain Size Distribution Experiment(Click here)) experiment, the flash view is not displaying in the small screen.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i23](https://cloud.githubusercontent.com/assets/13479177/26480821/3dcea5d8-41fa-11e7-8a25-4514decc5465.png)

**Comment by BSravanthi** [comment]
Referring to #76. As there is a difference in naming.

**Comment by sravanthimodepu** [comment]
Flash simulations is displaying on the small screen. Hence differing the issue.

**Comment by BSravanthi** [comment]
Closed #77
