### ISSUE TITLE
QA_soil-mechanics_Grain Size Distribution Experiment_Quizzes_Irrelevant-questions-are-given

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/soil-mechanics-and-foundation-engineering-iiith#78]
Defect Description :
The questions provided in the Quizzes page of "Grain Size Distribution Experiment" experiment,  are irrelevant to the present experiment. Where as in the vlabs page the questions are relevant to the experiment. 

Actual Result :
The questions provided in the Quizzes page of "Grain Size Distribution Experiment" experiment,  are irrelevant to the present experiment. Refer to the image that provided in the attachments.  

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i24](https://cloud.githubusercontent.com/assets/13479177/26480973/76371724-41fb-11e7-9852-2e5e15a20966.png)

**Comment by BSravanthi** [comment]
Once the issue is resolved can test rest of the segments in Quizzes section.

**Comment by sravanthimodepu** [comment]
Removed the quiz questions which has special characters ie., 1, 5 ,7, 8 & 9 questions.
