### ISSUE TITLE
QA_Soil-mechanics_Grain Size Distribution Experiment_Procedure_improper-alignment-for-numbering

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#79]
Defect Description :
In the Procedure page of "Grain Size Distribution Experiment" experiment, the alignment of the numbering can be given even more neatly. To maintain the look and feel of the page need to correct the alignment. 

Actual Result :
In the Procedure page of "Grain Size Distribution Experiment" experiment, the alignment of the numbering is improper. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i25](https://cloud.githubusercontent.com/assets/13479177/26481111/5c23d056-41fc-11e7-803b-55df91041e19.png)

**Comment by sravanthimodepu** [comment]
Aligned the procedure in order to look in a better way. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #79
