### ISSUE TITLE
QA_Soil-mechanics_Atterberg Limits Distribution Experiment_Theory_read-more-link-is-missed

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#81]
Defect Description :
In the Theory page of "Atterberg Limits Distribution Experiment" experiment, while porting the read more button is not included. How ever in the vlabs page the link is given in the theory page of the experiment.

Actual Result :
In the Theory page of "Atterberg Limits Distribution Experiment" experiment, while porting the read more button is not included. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i27](https://cloud.githubusercontent.com/assets/13479177/26481405/6a9bda50-41fe-11e7-9bde-6525ec3b047b.png)

**Comment by sravanthimodepu** [comment]
Added Readmore link to the page. Hence the issue is fixed.

**Comment by BSravanthi** [comment]
Closed #81
