### ISSUE TITLE
QA_Soil-mechanics_Atterberg Limits Experiment_Manual_content-may-need-to-upgrade

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#82]
Defect Description :
In the Manual page of "Atterberg Limits Experiment" experiment, the content may need to upgrade as the given content seems incomplete. 

Actual Result :
In the Manual page of "Atterberg Limits Experiment" experiment, the content may need to upgrade as the given content seems incomplete. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i28](https://cloud.githubusercontent.com/assets/13479177/26481673/671c5984-4200-11e7-8041-826cfaefab99.png)

**Comment by sravanthimodepu** [comment]
Experiment's manual is given in the **Readmore** link.

**Comment by BSravanthi** [comment]
Need not to be differed the issue as the "Data to be finalised." phrase need not be included in the section.

**Comment by sravanthimodepu** [comment]
Updated the proper content in the manual page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #82
