### ISSUE TITLE
QA_Soil-mechanics_Atterberg Limits Experiment_Quizzes_improper-alignment-for-numbering

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#83]
Defect Description :
In the Quizzes page of "Atterberg Limits Experiment" experiment, the alignment of the numbering can be given even more neatly. To maintain the look and feel of the page need to correct the alignment.

Actual Result :
In the Quizzes page of "Atterberg Limits Experiment" experiment, the alignment of the numbering is improper.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i29](https://cloud.githubusercontent.com/assets/13479177/26481832/3af6724e-4201-11e7-9ed3-171d8a814cf2.png)

**Comment by sravanthimodepu** [comment]
The alignment of the numbering is given properly. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #83
