### ISSUE TITLE
QA_soil-mechanics_Atterberg Limits Experiment_Procedure_Irrelevant-content

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#84]
Defect Description :
In the procedure section of "Atterberg Limits  Experiment" - irrelevant content is given. For the better usability for the user need to update the content.

Actual Result :
In the procedure section of "Atterberg Limits  Experiment" - irrelevant content is given.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i30](https://cloud.githubusercontent.com/assets/13479177/26481956/f88ec4dc-4201-11e7-88b0-97eb01fd23a0.png)

**Comment by sravanthimodepu** [comment]
Procedure is give in **Readmore** link.

**Comment by BSravanthi** [comment]
Re opening as the content "Data to be clarified" needs clarification.

**Comment by sravanthimodepu** [comment]
Updated the proper content in the procedure. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #84
