### ISSUE TITLE
QA_Soil-mechanics_Attenberg Limits Experiment_Further-readings_broken-links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#85]
Defect Description :
In the Further readings page of "Attenberg Limits Experiment" experiment, the 4th and 6th links are navigating to error pages.

Actual Result :
In the Further readings page of "Attenberg Limits Experiment" experiment, the 4th and 6th links are navigating to error pages.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i31](https://cloud.githubusercontent.com/assets/13479177/26482066/ccc98110-4202-11e7-8928-f643ba47468d.png)

**Comment by sravanthimodepu** [comment]
Updated the 6th link and 4th link is showing an error page, hence removed 4th link.

**Comment by BSravanthi** [comment]
Issue reopened as mentioned in the above comment, not only the 4th link but also the 6th link has been removed.

**Comment by sravanthimodepu** [comment]
Removed the 6th link too from the further readings. Hence resolve the issue.

**Comment by BSravanthi** [comment]
Closed #85
