### ISSUE TITLE
QA_Soil-mechanics_Permeability Experiment_Introduction_improper-alignment

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#86]
Defect Description :
In the Introduction page of "Permeability Experiment" experiment, the alignment of the content is improper.

Actual Result :
In the Introduction page of "Permeability Experiment" experiment, the alignment of the content is improper.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i32](https://cloud.githubusercontent.com/assets/13479177/26482931/c54d7310-4207-11e7-82b7-ac39e6e6f199.png)

**Comment by sravanthimodepu** [comment]
Resolved the issue.

**Comment by BSravanthi** [comment]
Closed #86
