### ISSUE TITLE
QA_soil-mechanics_Permeability Experiment_Experiment_flash-view-is-disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#87]
Defect Description :
In the Flash view unit of Experiment section in "Permeability Experiment" - (Flash view on Permeability Experiment(Click here)) experiment, the flash view is not displaying in the small screen. Where as the flash view is opening in full screen.

Actual Result :
In the Flash view unit of Experiment section in "Permeability Experiment" - (Flash view on Permeability Experiment(Click here)) experiment, the flash view is not displaying in the small screen.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i33](https://cloud.githubusercontent.com/assets/13479177/26483075/d46c4640-4208-11e7-9a56-62a601852b61.png)

**Comment by sravanthimodepu** [comment]
Flash simulation is displaying on the small screen. Hence differing the issue

**Comment by BSravanthi** [comment]
Closed #87
