### ISSUE TITLE
QA_soil-mechanics_Compaction Test Experiment_flash-view_Name-differing

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#88]
Defect Description :
In the Flash view Unit of the Experiment section in "Compaction Test  Experiment" , the name of the unit is given as **Virtual lab on Compaction Test Experiment(Click here)**. But, on click-full screen, the link is navigating to Flash view of the experiment. Instead the naming should be appropriate to the animation.

Actual Result :
In the Flash view Unit of the Experiment section in "Compaction Test  Experiment" , the name of the unit is given as **Virtual lab on Compaction Test Experiment(Click here)**. But, on click-full screen, the link is navigating to Flash view of the experiment. Instead the naming should be appropriate to the animation.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i34](https://cloud.githubusercontent.com/assets/13479177/26483583/6e9422d6-420b-11e7-8e34-12acbe9f1089.png)

**Comment by sravanthimodepu** [comment]
Updated the name according to the simulation. Hence issue is fixed.

**Comment by BSravanthi** [comment]
Re opening the issue as removal of name is not a suggested solution as there are two units in the experiment section and the user may be in confusion.

**Comment by sravanthimodepu** [comment]
Updated the appropriate name for the experiment. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #88
