### ISSUE TITLE
QA_soil-mechanics_Compaction Test Experiment_Experiment_flash-view-is-disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#89]
Defect Description :
In the Flash view unit of Experiment section in "Compaction Test Experiment" - (Flash view on Compaction Test Experiment(Click here)) experiment, the flash view is not displaying in the small screen. Where as the flash view is opening in full screen.

Actual Result :
In the Flash view unit of Experiment section in "Compaction Test Experiment" - (Flash view on Compaction Test Experiment(Click here)) experiment, the flash view is not displaying in the small screen.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i34](https://cloud.githubusercontent.com/assets/13479177/26483673/e03f90d2-420b-11e7-82ff-5aeaeac3d00f.png)

**Comment by sravanthimodepu** [comment]
Flash simulation is displaying on the  small screen. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Bug still existed. Hence reopening the issue.
