### ISSUE TITLE
QA_Consolidation Test_Experiment_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#9]
Defect Description :
In the Experiment page of "Consolidation Test " experiment, when we click on the "Consolidation Test Experiment" link, it is redirecting to a blank page instead it should redirect to an experiment page  in-order to perform the simulation of the experiment

Actual Result :
In the Experiment page of "Consolidation Test " experiment, when we click on the "Consolidation Test Experiment" link, it is redirecting to a blank page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith/blob/master/test-cases/integration_test-cases/Consolidation%20Test/Consolidation%20Test_10_Experiment_p1.org

Attachment:

![sm38](https://cloud.githubusercontent.com/assets/14869397/14779546/36557c3c-0af6-11e6-8dd1-f2b2a53427aa.png)

**Comment by khushpreet-kaur** [comment]
Link is working fine now.

**Comment by BSravanthi** [comment]
Closed #9
