### ISSUE TITLE
QA_Soil-mechanics_Compaction Test Experiment_Quizzes_check-button-functionality-defect

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/soil-mechanics-and-foundation-engineering-iiith#90]
Defect Description :
In the Quizzes page of "Compaction Test Experiment" experiment, found functionality defect with the check button.

Actual Result :
In the Quizzes page of "Compaction Test Experiment" experiment, found functionality defect with the check button. Check button is not accessible. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i35](https://cloud.githubusercontent.com/assets/13479177/26484035/c3e7a710-420d-11e7-96a7-2f6a7ea31cf5.png)

**Comment by sravanthimodepu** [comment]
Made changes to the check button and it is accessible now. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Issue still not fixed. Hence re opening. 

![qa_oe_sm_i62](https://user-images.githubusercontent.com/13479177/27725781-8ac42d48-5d95-11e7-8217-770f9aedd74e.png)
