### ISSUE TITLE
QA_Soil-mechanics_Compaction Test Experiment_Procedure_improper-alignment-for-numbering

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#91]
Defect Description :
In the Procedure page of "Compaction Test Experiment" experiment, the alignment of the numbering can be given even more neatly. To maintain the look and feel of the page need to correct the alignment.

Actual Result :
In the Procedure page of "Compaction Test Experiment" experiment, the alignment of the numbering is improper.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i36](https://cloud.githubusercontent.com/assets/13479177/26484146/3014367e-420e-11e7-8e91-d3c3844d6516.png)

**Comment by sravanthimodepu** [comment]
Given proper numbering for the procedure steps. Hence issue is fixed.

**Comment by BSravanthi** [comment]
Reopening the issue as in (vi) point, instead of fir - suggested Fill might be an appropriate word.

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistakes in the procedure section. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #91
