### ISSUE TITLE
QA_soil-mechanics_Consolidation Test Experiment_Experiment_flash-view-is-disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#92]
Defect Description :
In the Flash view unit of Experiment section in "Consolidation Test Experiment" - (Flash view on Consolidation Test Experiment(Click here)) experiment, the flash view is not displaying in the small screen. Where as the flash view is opening in full screen.

Actual Result :
In the Flash view unit of Experiment section in "Consolidation Test Experiment" - (Flash view on Consolidation Test Experiment(Click here)) experiment, the flash view is not displaying in the small screen.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i37](https://cloud.githubusercontent.com/assets/13479177/26484951/8412db82-4212-11e7-8327-f6802243accf.png)

**Comment by sravanthimodepu** [comment]
Flash view of this experiment is displaying on the small screen. Hence differing
![consolidation](https://user-images.githubusercontent.com/11156924/27635257-e8ba98a6-5c23-11e7-8c72-8a1d55c88bec.png)
 this issue.

**Comment by BSravanthi** [comment]
Issue is not deferred as shown in the screen shot of my comment.

**Comment by BSravanthi** [comment]
Closed #92
As now the flash view is enabled in small screen.
