### ISSUE TITLE
QA_Soil-mechanics_Consolidation Test Experiment_Quizzes_improper-alignment-of-questions

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#93]
Defect Description :
In the Quizzes page of "Consolidation Test Experiment" experiment, the alignment of the 2nd and 3rd questions is improper.

Actual Result :
In the Quizzes page of "Consolidation Test Experiment" experiment, the alignment of the 2nd and 3rd questions is improper.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i38](https://cloud.githubusercontent.com/assets/13479177/26485057/09fe9c0e-4213-11e7-8455-44a6e369478b.png)

**Comment by sravanthimodepu** [comment]
Aligned the questions properly. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Re opening the issue as the quizzes sections now after fixing this issue left with no questions.

**Comment by sravanthimodepu** [comment]
Added the quizzes to the quiz section. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #93
