### ISSUE TITLE
QA_soil-mechanics_Consolidation Experiment_Procedure_Irrelevant-content

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#94]
Defect Description :
In the procedure section of "Consolidation Experiment" - irrelevant content is given. For the better usability for the user need to update the content.

Actual Result :
In the procedure section of "Consolidation Experiment" - irrelevant content is given. The table that has given in manual section itself is given in the procedure section too. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i39](https://cloud.githubusercontent.com/assets/13479177/26485179/9be1b3fe-4213-11e7-876d-4fa72712e7bf.png)

**Comment by sravanthimodepu** [comment]
Procedure is given in the **Readmore** link which is below the table.

**Comment by BSravanthi** [comment]
Closed #94
