### ISSUE TITLE
QA_Soil-mechanics_Consolidation Test Experiment_Further-readings_irrelevant-content/content-needs-to-be-updated

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#95]
Defect Description :
In the Further readings page of "Consolidation Test Experiment" experiment, the content needs to be updated.

Actual Result :
In the Further readings page of "Consolidation Test Experiment" experiment, the content needs to be updated.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i40](https://cloud.githubusercontent.com/assets/13479177/26485254/fb86709c-4213-11e7-8e10-b8b590f603fc.png)

**Comment by sravanthimodepu** [comment]
As there is no content in the page, removing the further section from the experiment.

**Comment by BSravanthi** [comment]
Closed #95
