### ISSUE TITLE
QA_Order-of-the-menu_Compaction Test Experiment

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#97]
Defect Description :
The order of the menu items for this experiment is not in desired order. Need to correct the order to "Introduction, Theory, Objective, Manual, Procedure, Experiment, Quizzes, Further Readings and Feedback".

Actual Result :
The order of the menu items for this experiment is not in desired order. The order of the menu items are given as "Introduction, Theory, Objective, Experiment, Manual, Quizzes, Procedure, Further Readings, Feedback"

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i42](https://cloud.githubusercontent.com/assets/13479177/26486924/c955b072-421a-11e7-83a2-0b263eb2390c.png)

**Comment by sravanthimodepu** [comment]
The order of the menu items arranged as given"Introduction, Theory, Objective, Manual, Procedure, Experiment, Quizzes, Further readings and Feedback". Hence issue is resolved

**Comment by BSravanthi** [comment]
Closed #97
